# Generated by Django 3.2.25 on 2024-05-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_has_sizes_thing_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='featured_image',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to=''),
        ),
    ]
