# Generated by Django 3.2.25 on 2024-05-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_thing_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='slug',
            new_name='sku',
        ),
    ]
