# Generated by Django 3.2.25 on 2024-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_slug_thing_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='sku',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
