# Generated by Django 3.2.25 on 2024-05-22 10:09

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_thing_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='sku',
            field=models.CharField(default=products.models.sku_default, max_length=200, unique=True),
        ),
    ]
